name: "youtuber_analysis"
version: "1.0.0"
config-version: 2

profile: "youtuber_analysis"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  youtuber_analysis:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
